name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the base Docker
      working-directory: ./dockerfiles/cpp_base
      run: docker build . --file Dockerfile --tag graugans/cpp:base
    - name: docker login

      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker push cpp base
      run: docker push ghcr.io/graugans/cpp:base